# Generated by Django 3.1.4 on 2021-06-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='web',
            options={'verbose_name_plural': 'Web Projects'},
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
