# Generated by Django 3.1.4 on 2021-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0002_auto_20210628_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='nivel',
            field=models.IntegerField(default=50),
        ),
    ]
