# Generated by Django 3.1.4 on 2021-08-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0003_skills_nivel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Illustration',
            new_name='Art',
        ),
        migrations.RenameModel(
            old_name='Web',
            new_name='Project',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Projects'},
        ),
    ]
