# Generated by Django 3.1.4 on 2021-08-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0004_auto_20210810_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
