# Generated by Django 3.1.4 on 2022-01-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('david', '0005_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comic',
        ),
    ]
